#!/bin/bash

IFS=$'\n'

while read -r line; do
    # Split the line into fields using colon as the delimiter
    username=$(echo "$line" | cut -d':' -f1)
    password=$(echo "$line" | cut -d':' -f2)
    uid=$(echo "$line" | cut -d':' -f3)
    gid=$(echo "$line" | cut -d':' -f4)
    user_info=$(echo "$line" | cut -d':' -f5)
    home_directory=$(echo "$line" | cut -d':' -f6)
    shell=$(echo "$line" | cut -d':' -f7)

    echo "The user $username is part of the $gid gang, lives in $home_directory and rides $shell. $uid's place is protected by the passcode $password, more info about the user here: $user_info"
done < /etc/passwd

