#!/usr/bin/env bash
# The Bash script creates a PID file, displays a message indefinitely, and handles signals with specific actions. It displays different messages for SIGINT and SIGTERM, and removes the PID file before exiting.

ender() {
    rm /var/run/myscript.pid
    exit
}

trap "echo I hate the kill command;ender" SIGTERM
trap "echo Y U no love me?!" SIGINT
trap ender SIGQUIT

echo "$$" > /var/run/myscript.pid

while true; do
    echo "To infinity and beyond"
    sleep 2
done
