#!/usr/bin/env bash
# A Bash script that stops 4-to_infinity_and_beyond process.
# shellcheck disable=SC2009
pid=$(ps -aux | grep ./4-to_infinity_and_beyond | head -n 1 | awk '{print $2}')
kill "$pid"