#!/usr/bin/env bash
# A Bash script that displays To infinity and beyond indefinitely, intercepting SIGTERM signals
_invincible() {
    echo "I am invincible!!!"
}
trap _invincible SIGTERM

while (( 1 == 1 )); do
    echo "To infinity and beyond"
    sleep 2
done
